// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Trainer_ml
{
    public partial class Y00tPricePrediction
    {
        /// <summary>
        /// model input class for Y00tPricePrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Background")]
            public string Background { get; set; }

            [ColumnName(@"Fur")]
            public string Fur { get; set; }

            [ColumnName(@"Face")]
            public string Face { get; set; }

            [ColumnName(@"Clothes")]
            public string Clothes { get; set; }

            [ColumnName(@"Eyewear")]
            public string Eyewear { get; set; }

            [ColumnName(@"Head")]
            public string Head { get; set; }

            [ColumnName(@"Unique")]
            public bool Unique { get; set; }

            [ColumnName(@"DateTime")]
            public DateTime DateTime { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Y00tPricePrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Background")]
            public float[] Background { get; set; }

            [ColumnName(@"Fur")]
            public float[] Fur { get; set; }

            [ColumnName(@"Face")]
            public float[] Face { get; set; }

            [ColumnName(@"Clothes")]
            public float[] Clothes { get; set; }

            [ColumnName(@"Eyewear")]
            public float[] Eyewear { get; set; }

            [ColumnName(@"Head")]
            public float[] Head { get; set; }

            [ColumnName(@"Unique")]
            public float Unique { get; set; }

            [ColumnName(@"DateTime")]
            public float DateTime { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("y00tPricePrediction.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
